package:
  name: pydantic_core
  version: 2.27.2
  tag:
    - rust
  # Warning: pydantic has a pin on pydantic_core, they need to be updated
  # together
  top-level:
    - pydantic_core
source:
  git_url: https://github.com/koxudaxi/pydantic-core.git
  git_rev: 1bf2082c11cb672a7646d491d1022fb365af926d
requirements:
  run:
    - typing-extensions
  executable:
    - rustup
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
