package:
  name: pydantic_core
  version: 2.27.2
  tag:
    - rust
  # Warning: pydantic has a pin on pydantic_core, they need to be updated
  # together
  top-level:
    - pydantic_core
source:
  url: https://github.com/pydantic/pydantic-core/archive/1bf2082c11cb672a7646d491d1022fb365af926d.tar.gz
  sha256: 075101e62db16266e9c3418143492d1f9f012b0f84d9e11df00ec3053fb599b8
requirements:
  run:
    - typing-extensions
  executable:
    - rustup
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
