package:
  name: pydantic_core
  version: 2.34.1
  tag:
    - rust
  # Warning: pydantic has a pin on pydantic_core, they need to be updated
  # together
  top-level:
    - pydantic_core
source:
  url: https://github.com/koxudaxi/pydantic-core/archive/8b3bdfa2729f00a31f6b5fab5e4d21fb4a71ff53.tar.gz
  sha256: b91d186639df7af84dfc5d6c45c6606e35da0d78100081e987c88b96ea6e8dae
requirements:
  run:
    - typing-extensions
  executable:
    - rustup
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
