package:
  name: pydecimal
  version: 1.0.0 # Nonsense
  tag:
    - always
  top-level:
    - _pydecimal
source:
  path: ../../cpython/build/Python-3.14.0a1
build:
  type: cpython_module
  script: |
    cp Lib/_pydecimal.py $DISTDIR
