package:
  name: matplotlib
  version: 3.8.4
  tag:
    - min-scipy-stack
  top-level:
    - pylab
    - mpl_toolkits
    - matplotlib
source:
  url: https://files.pythonhosted.org/packages/2f/08/b89867ecea2e305f408fbb417139a8dd941ecf7b23a2e02157c36da546f0/matplotlib-3.10.1.tar.gz
  sha256: e8d2d0e3881b129268585bf4765ad3ee73a4591d77b9a18c214ac7e3a79fb2ba
  patches:
#    - patches/0001-Disable-macOS-X-backend.patch
    - patches/0002-Disable-timer.patch
    - patches/0003-Hardcode-font-cache-path.patch
  extras:
    - - extras/setup.cfg
      - ./mplsetup.cfg

build:
  # RELOCATABLE flag is required because if affects how emscripten build ports.
  cflags: |
    -s RELOCATABLE=1
    -s USE_FREETYPE=1
    -s USE_LIBPNG=1
    -s USE_ZLIB=1
    -fexceptions
    -fno-lto
  cxxflags: |
    -std=c++14
    -fexceptions
  ldflags: |
    -fexceptions
  script: export SETUPTOOLS_SCM_PRETEND_VERSION=$PKG_VERSION
  post: |
    rm -rf matplotlib/backends/qt_editor
    rm -rf matplotlib/backends/web_backend
    rm -rf sphinxext
    cp $PKGDIR/extras/fontlist.json matplotlib
    cp $PKGDIR/extras/Humor-Sans-1.0.ttf matplotlib/mpl-data/fonts/ttf/Humor-Sans.ttf
    mkdir -p $PKGDIR/../../dist/fonts
    cp matplotlib/mpl-data/fonts/ttf/* $PKGDIR/../../dist/fonts/

requirements:
  host:
    - numpy
  run:
    - contourpy
    - cycler
    - fonttools
    - kiwisolver
    - numpy
    - packaging
    - Pillow
    - pyparsing
    - python-dateutil
    - pytz
    - matplotlib-pyodide

about:
  home: https://matplotlib.org
  PyPI: https://pypi.org/project/matplotlib
  summary: Python plotting package
  license: PSF
