package:
  name: fiona
  version: 1.9.6
source:
  url: https://files.pythonhosted.org/packages/92/2c/2ab81e38aad8cf4f4e2a7b1c0488750ffc512c108fb244a8b4dd4f196cd3/fiona-1.9.6.tar.gz
  sha256: 791b3494f8b218c06ea56f892bd6ba893dfa23525347761d066fb7738acda3b1
test:
  imports:
    - fiona
    - fiona.fio
requirements:
  host:
    - gdal
    - geos
  run:
    - attrs
    - certifi
    - setuptools
    - six
    - click
    - cligj
      # - click-plugins  # only for fiona CLI?

build:
  vendor-sharedlib: true
  script: |
    export PACKAGE_DATA=1
    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG}
    echo ${GDAL_DATA}
    echo ${PROJ_LIB}
    rm tests/test_fio* # CLI tests
    rm tests/test_data_paths.py # CLI tests
    rm tests/test_datetime.py # CLI tests
    rm tests/test_vfs.py # No module named "boto3"
    rm tests/test_env.py # No module named "boto3"

    mkdir fiona-tests
    mv tests fiona-tests
    tar -cf ${DISTDIR}/fiona-tests.tar fiona-tests

about:
  home: http://github.com/Toblerity/Fiona
  PyPI: https://pypi.org/project/fiona
  summary: Fiona reads and writes spatial data files
  license: BSD
# Note: this package needs to be manually upgraded to the next version
