package:
  name: river
  version: 0.21.0
  top-level:
    - river

source:
  url: https://files.pythonhosted.org/packages/30/6e/acbd2d8b3516abdcba9ca06e4e58db4d7f424aaa93dc73956d8dd5eb24f5/river-0.21.0.tar.gz
  sha256: 692923bb8e35005cdbb422b490e2f6bac95cf4cf2fb7d00e1924a697c6a2b506

requirements:
  executable:
    - rustup
  host:
    - numpy
  run:
    - numpy
    - pandas
    - pytest # can remove in 0.20
    - scipy

about:
  home: https://github.com/online-ml/river
  PyPI: https://pypi.org/project/river
  summary: Online machine learning in Python
  license: BSD-3

test:
  imports:
    - river
    - river.api
extra:
  recipe-maintainers:
    - MaxHalford
