package:
  name: bitstring
  version: 4.2.0
  top-level:
    - bitstring
source:
  url: https://files.pythonhosted.org/packages/40/cb/ff7de9e1d8b6023f9d48621f4064c6536ce397118211fe28ebcdd03f6063/bitstring-4.2.0-py3-none-any.whl
  sha256: 9c40b6cbd1aede96077b8b2c82349eb69e0e3cbbc9bc4305035df38275521e10
requirements:
  run:
    - bitarray
about:
  home: ""
  PyPI: https://pypi.org/project/bitstring
  summary: Simple construction, analysis and modification of binary data.
  license: ""
