package:
  name: jiter
  version: 0.9.0
  top-level:
    - jiter
source:
  url: https://github.com/pydantic/jiter/archive/031eff074b7194e41485e957a5a399b884136d3c.tar.gz
  sha256: 027c61e6a04078493a9205f045fd3f52cde7e6af6bbdcea93b7283b580f15896
about:
  home: https://github.com/pydantic/jiter/tree/main/crates/jiter-python
  PyPI: https://pypi.org/project/jiter
  summary:
    Fast, safe JSON parser written in Rust with support for parsing partial
    JSON
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
