package:
  name: jiter
  version: 0.9.0
  top-level:
    - jiter
source:
  git_url: https://github.com/koxudaxi/jiter.git
  git_rev: 031eff074b7194e41485e957a5a399b884136d3c
  subdir: crates/jiter-python
about:
  home: https://github.com/pydantic/jiter/tree/main/crates/jiter-python
  PyPI: https://pypi.org/project/jiter
  summary:
    Fast, safe JSON parser written in Rust with support for parsing partial
    JSON
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
