package:
  name: executing
  version: 2.0.1
  tag:
    - core
  top-level:
    - executing
source:
  url: https://github.com/alexmojaki/executing/archive/refs/heads/3.13.tar.gz
  sha256: eac49ca94516ccc753f9fb5ce82603156e590b27525a8bc32cce8ae302eb61bc
about:
  home: https://github.com/alexmojaki/executing
  PyPI: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
build:
  script: |
    sed -i 's/)/,version="2.0.1")/' setup.py
    python3 -m build --wheel
