package:
  name: hashlib
  version: 1.0.0 # Nonsense
  tag:
    - always
  top-level:
    - _hashlib
source:
  path: ../../cpython/build/Python-3.14.0a1
build:
  type: cpython_module
  script: |
    emcc $STDLIB_MODULE_CFLAGS -c Modules/_hashopenssl.c -o Modules/_hashlib.o \
      $(pkg-config --cflags --dont-define-prefix libcrypto) -DOPENSSL_THREADS

    emcc Modules/_hashlib.o -o $DISTDIR/_hashlib.so $SIDE_MODULE_LDFLAGS \
      $(pkg-config --libs --dont-define-prefix libcrypto) -DOPENSSL_THREADS

requirements:
  run:
    - openssl
  host:
    - openssl
