package:
  name: ipython
  version: 9.2.0
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/9d/02/63a84444a7409b3c0acd1de9ffe524660e0e5d82ee473e78b45e5bfb64a4/ipython-9.2.0.tar.gz
  sha256: 62a9373dbc12f28f9feaf4700d052195bf89806279fc8ca11f3f54017d04751b
requirements:
  run:
    - asttokens
    - decorator
    - executing
    - matplotlib-inline
    - prompt_toolkit
    - pure-eval
    - Pygments
    - six
    - stack-data
    - traitlets
    - sqlite3
    - wcwidth
about:
  home: https://ipython.org
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
